server:
  port: 8801
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shanghao?characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123
  jackson:
    date-format: yyyy年MM月dd日 HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 300MB